name: CI

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */8 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    
    steps:
      - name: Install
        run: sudo -v ; curl https://rclone.org/install.sh | sudo bash

      - name: Save
        run: |
          mkdir -p ~/.config/rclone
          cat << EOF > ~/.config/rclone/rclone.conf
          ${{ secrets.CONFIG }}
          EOF

      - name: Run
        run: ${{ secrets.COMMAND }}
